language: python
python:
  - "3.6"
env:
  global:
    - "MYSQL_DATABASE=irida_uploader_test"
    - "MYSQL_USER=test"
    - "MYSQL_PASSWORD=test"
    - "DB_MAX_WAIT_MILLIS=30000"
  matrix:
    - "TEST_SUITE=unit"
    - "TEST_SUITE=integration_master"
    - "TEST_SUITE=integratino_dev"
addons:
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - sudo apt-get install -y xvfb
  - rm -rf tests_integration/repos/
  - mkdir tests_integration/tmp
  - mkdir tests_integration/tmp/output-files
  - mkdir tests_integration/tmp/reference-files
  - mkdir tests_integration/tmp/sequence-files
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
install:
  - pip install --upgrade pip wheel
  - pip install -r requirements.txt
  - mysql -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'localhost';"
script:
  - ./travis_test.sh
