#language: python
#python:
#  - "3.6"
## command to install dependencies
#install:
#  - pip install --upgrade pip wheel
#  - pip install -r requirements.txt
#script:
#  - python3 -m unittest discover -s tests -t .
language: python
python:
  - "3.6"
env:
  global:
    - "MYSQL_DATABASE=irida_uploader_test"
    - "MYSQL_USER=test"
    - "MYSQL_PASSWORD=test"
    - "DB_MAX_WAIT_MILLIS=30000"
addons:
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - sudo apt-get install -y xvfb
  - rm -rf tests_integration/repos/
  - mkdir tests_integration/tmp
  - mkdir tests_integration/tmp/output-files
  - mkdir tests_integration/tmp/reference-files
  - mkdir tests_integration/tmp/sequence-files
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
#  - "export PATH=$PATH:/usr/lib/chromium-browser/"
# command to install dependencies
install:
  - pip install --upgrade pip wheel
  - pip install -r requirements.txt
  - mysql -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'localhost';"
script:
  - xvfb-run --auto-servernum --server-num=1 python3 start_integration_tests.py
